In [3]:
%matplotlib notebook

import numpy as np
import matplotlib.pyplot as plt
from astropy.io import ascii
from astropy.table import Table
from scipy.interpolate import interp1d 
from astropy.modeling.tabular import tabular_model

In [33]:
table = np.array([[0., 1., 2.],
                  [3., 4., 5.],
                  [6., 7., 8.]])

In [34]:
table.shape

(3, 3)

In [35]:
tab = tabular_model(2, name='Tabular2D')
print(tab)

<class 'abc.Tabular2D'>
Name: Tabular2D
Inputs: ('x0', 'x1')
Outputs: ('y',)


In [37]:
points = ([1, 2, 3], [1, 2, 3])

In [52]:
m = tab(points, lookup_table=table, name='my_table', bounds_error=False, fill_value=None, method='linear')

In [53]:
xinterp = [0, 1, 1.5, 2.72, 3.14]
xinterp = [1,2,1.6]
m(xinterp, xinterp)  

array([ 0. ,  4. ,  2.4])

In [54]:
m([1],[2.5])

array([ 1.5])

# 1D table


In [24]:
table1D = np.array([3., 7., 1., 6., 12.])

In [25]:
tab1 = tabular_model(1, name='Tabular1D')
print(tab1)

<class 'abc.Tabular1D'>
Name: Tabular1D
Inputs: ('x0',)
Outputs: ('y',)


In [26]:
points = ([1, 2, 3, 4, 5])

In [31]:
m1 = tab1(points, lookup_table=table1D, name='my_table', bounds_error=False, fill_value=None, method='linear')

In [32]:
xinterp = [0, 1, 1.5, 2.72, 3.14, 5.5]
m1(xinterp)  

array([ -1.  ,   3.  ,   5.  ,   2.68,   1.7 ,  15.  ])